export const icons = {
  eth: require('./icons/eth.png'),
  btc: require('./icons/btc.png'),
  avax: require('./icons/avax.png'),
  bnb: require('./icons/bnb.png'),
  usdt: require('./icons/usdt.png'),
  send: require('./icons/send.png'),
  qr_code: require('./icons/qr_code.png'),
  home_focus: require('./icons/home_focus.png'),
  receipt: require('./icons/receipt.png'),
  table: require('./icons/table.png'),
  table_focus: require('./icons/table_focus.png'),
  highlight: require('./icons/highlight.png'),
  star: require('./icons/star.png'),
  search: require('./icons/search.png'),
  location: require('./icons/location.png'),
  avatar: require('./icons/avatar.png'),
  down_arrow: require('./icons/down_arrow.png'),
  heart: require('./icons/heart.png'),
  cart: require('./icons/cart.png'),
  food_1: require('./icons/food_1.png'),
  food_2: require('./icons/food_2.png'),
  food_3: require('./icons/food_3.png'),
};
