export default {
  //root main
  AUTH_CONTAINER: 'AUTH_CONTAINER',
  BOTTOM_CONTAINER: 'BOTTOM_CONTAINER',
  COMMON_CONTAINER: 'COMMON_CONTAINER',

  //bottom container
  HOME_SCREEN: 'HOME_SCREEN',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  WALLET_SCREEN: 'WALLET_SCREEN',

  //common container
  DETAIL_SCREEN: 'DETAIL_SCREEN',
  CHART_SCREEN: 'CHART_SCREEN',
};
