export default {
  //root main
  AUTH_NAVIGATION: 'AUTH_NAVIGATION',
  BOTTOM_NAVIGATION: 'BOTTOM_NAVIGATION',
  COMMON_NAVIGATION: 'COMMON_NAVIGATION',

  //bottom container
  HOME_SCREEN: 'HOME_SCREEN',
  ACCOUNT_SCREEN: 'ACCOUNT_SCREEN',
  WALLET_SCREEN: 'WALLET_SCREEN',

  //auth container
  SIGN_IN_SCREEN: 'SIGN_IN_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',

  //common container
  DETAIL_PLACE_SCREEN: 'DETAIL_PLACE_SCREEN',
  CHART_SCREEN: 'CHART_SCREEN',
};
