export const icons = {
  //common icons
  eth: require('./icons/eth.png'),
  btc: require('./icons/btc.png'),
  avax: require('./icons/avax.png'),
  bnb: require('./icons/bnb.png'),
  usdt: require('./icons/usdt.png'),
  send: require('./icons/send.png'),
  qr_code: require('./icons/qr_code.png'),
  receipt: require('./icons/receipt.png'),
  highlight: require('./icons/highlight.png'),
  star: require('./icons/star.png'),
  location: require('./icons/location.png'),
  avatar: require('./icons/avatar.png'),
  heart: require('./icons/heart.png'),
  white_heart: require('./icons/white_heart.png'),
  cart: require('./icons/cart.png'),

  youtube_logo_big: require('./AppIcons/youtube_logo_big.png'),
  youtube_logo: require('./AppIcons/youtube_logo.png'),
  explore: require('./AppIcons/explore.png'),
  connect_tv: require('./AppIcons/connect_tv.png'),
  bell: require('./AppIcons/bell.png'),
  more: require('./AppIcons/more.png'),
  search: require('./AppIcons/search.png'),
  short_red: require('./AppIcons/short_red.png'),
  camera: require('./AppIcons/camera.png'),
  music: require('./AppIcons/music.png'),
  share: require('./AppIcons/share.png'),
  like: require('./AppIcons/like.png'),
  dislike: require('./AppIcons/dislike.png'),
  comment: require('./AppIcons/comment.png'),
  remix: require('./AppIcons/remix.png'),
  soundImage: require('./AppIcons/soundImage.png'),
  auto_play: require('./AppIcons/auto_play.png'),
  bell_muted: require('./AppIcons/bell_muted.png'),
  cut_outline: require('./AppIcons/cut_outline.png'),
  disabled_outline: require('./AppIcons/disabled_outline.png'),
  dislike_outline: require('./AppIcons/dislike_outline.png'),
  down_arrow: require('./AppIcons/down_arrow.png'),
  download_outline: require('./AppIcons/download_outline.png'),
  full_screen: require('./AppIcons/full_screen.png'),
  like_outline: require('./AppIcons/like_outline.png'),
  save_outline: require('./AppIcons/save_outline.png'),
  share_outline: require('./AppIcons/share_outline.png'),
  subtitle: require('./AppIcons/subtitle.png'),
  settings: require('./AppIcons/settings.png'),
  continues: require('./AppIcons/continues.png'),
  pause: require('./AppIcons/pause.png'),
  next: require('./AppIcons/next.png'),
  previous: require('./AppIcons/previous.png'),
  upload: require('./AppIcons/upload.png'),
  goLive: require('./AppIcons/goLive.png'),
  edit: require('./AppIcons/edit.png'),
  close: require('./AppIcons/close.png'),
  avatar_2: require('./AppIcons/avatar_2.png'),
  playList: require('./AppIcons/playList.png'),
  playBack: require('./AppIcons/playBack.png'),
  isShort: require('./AppIcons/isShort.png'),
  arrow_back: require('./AppIcons/arrow_back.png'),
  arrow_pick: require('./AppIcons/arrow_pick.png'),
  record: require('./AppIcons/record.png'),

  //bottom bar icons
  home_focus: require('./AppIcons/home_focus.png'),
  home: require('./AppIcons/home.png'),
  short_focus: require('./AppIcons/short_focus.png'),
  short: require('./AppIcons/short.png'),
  create: require('./AppIcons/create.png'),
  subscribe: require('./AppIcons/subscribe.png'),
  subscribe_focus: require('./AppIcons/subscribe_focus.png'),
  library: require('./AppIcons/library.png'),
  library_focus: require('./AppIcons/library_focus.png'),

  // common img
  food_1: require('./icons/food_1.png'),
  food_2: require('./icons/food_2.png'),
  food_3: require('./icons/food_3.png'),

  //video
  video_1: require('./video/video_1.mp4'),
  short_1: require('./video/short_1.mp4'),
  short_2: require('./video/short_2.mp4'),
};
