export default {
  //root main
  AUTH_NAVIGATION: 'AUTH_NAVIGATION',
  BOTTOM_NAVIGATION: 'BOTTOM_NAVIGATION',
  COMMON_NAVIGATION: 'COMMON_NAVIGATION',

  //bottom container
  HOME_SCREEN: 'HOME_SCREEN',
  SHORT_SCREEN: 'SHORT_SCREEN',
  SUBSCRIPTION: 'SUBSCRIPTION',
  LIBRARY: 'LIBRARY',

  ACCOUNT_SCREEN: 'ACCOUNT_SCREEN',
  WALLET_SCREEN: 'WALLET_SCREEN',

  //auth container
  SIGN_IN_SCREEN: 'SIGN_IN_SCREEN',
  SIGN_UP_SCREEN: 'SIGN_UP_SCREEN',

  //common container
  VIDEO_DETAIL_SCREEN: 'VIDEO_DETAIL_SCREEN',
  LISTING_VIDEO_SCREEN: 'LISTING_VIDEO_SCREEN',
  SEARCH_SCREEN: 'SEARCH_SCREEN',
};
